# -*- coding: utf-8 -*-
#################
import numpy as np
import pandas as pd
import csv
from csv import writer

from ..core.smps import SMPS
from ..config import get_metadata, get_instrument_header
from .read_aux import smps_file_to_config, opc_file_to_config
#################

"""
mysmps.io.csv_write
==================

Functions for reading of csv files:
    write_aim_csv

Created on Wed Sep 30 12:00 2020

@author: flovan / fvanden

Revision history:   30.09.2020 - Created


"""
def write_aim_csv(smps, fileorg = 'AIM', **kwargs):
    """
    Writes SMPS object to a csv file in the same organisation
    as the file generated by the AIM software
    
    Parameters
    ----------
    smps - SMPS
        core.SMPS object to use for creating plots
        
    fileorg : str
        different file organisations can be found in the default_config
        for new filetypes add mappings here and specify the filetype
        
    kwargs : 
        
        
    Returns
    -------
    None
    """
    pass